// PornMake Multi-language Translations
const translations = {
    en: {
        title: "Porn Make",
        tagline: "Make Best Porn Ever",
        subtitle: "AI integrated platform for creating high quality content",
        download: "Download App",
        copyLink: "Copy Link",
        copied: "Copied!",
        welcome: "Welcome to Porn Make",
        createMore: "Create More Like This",
        shareText: "Share Porn Make with others Too. Copy the link and share with others.",
        linkToCopy: "Lets Create best Porn Ever. Follow the Link.",
        features: "Features",
        featuresSub: "Everything you need to create amazing content",
        ready: "Ready to Create?",
        readySub: "Join thousands of creators making amazing content",
        downloadLarge: "Download Porn Make",
        free: "Free to use",
        noRegistration: "No registration required",
        allDevices: "Works on all devices",
        safe: "Safe & secure",
        visitSite: "Visit Website",
        footerNote: "Made with ❤️ for content creators",
        madeBy: "AI-powered content creation"
    },
    ar: {
        title: "Porn Make",
        tagline: "اصنع أفضل إباحي على الإطلاق",
        subtitle: "منصة مدعومة بالذكاء الاصطناعي لإنشاء محتوى عالي الجودة",
        download: "تحميل التطبيق",
        copyLink: "نسخ الرابط",
        copied: "تم النسخ!",
        welcome: "مرحبًا بك في Porn Make",
        createMore: "إنشاء المزيد مثل هذا",
        shareText: "شارك Porn Make مع الآخرين أيضًا. انسخ الرابط وشاركه مع الآخرين.",
        linkToCopy: "لنصنع أفضل إباحي على الإطلاق. اتبع الرابط.",
        features: "الميزات",
        featuresSub: "كل ما تحتاجه لإنشاء محتوى مذهل",
        ready: "هل أنت مستعد للإنشاء؟",
        readySub: "انضم إلى آلاف المنشئين الذين يصنعون محتوى مذهلاً",
        downloadLarge: "تحميل Porn Make",
        free: "استخدام مجاني",
        noRegistration: "لا يتطلب التسجيل",
        allDevices: "يعمل على جميع الأجهزة",
        safe: "آمن ومحمي",
        visitSite: "زيارة الموقع",
        footerNote: "صنع بـ ❤️ لمنشئي المحتوى",
        madeBy: "إنشاء محتوى مدعوم بالذكاء الاصطناعي"
    },
    es: {
        title: "Porn Make",
        tagline: "Crea el Mejor Porn Siempre",
        subtitle: "Plataforma integrada con IA para crear contenido de alta calidad",
        download: "Descargar Aplicación",
        copyLink: "Copiar Enlace",
        copied: "¡Copiado!",
        welcome: "Bienvenido a Porn Make",
        createMore: "Crea Más Como Esto",
        shareText: "Comparte Porn Make con otros también. Copia el enlace y compártelo con otros.",
        linkToCopy: "Creemos el mejor porno siempre. Sigue el enlace.",
        features: "Características",
        featuresSub: "Todo lo que necesitas para crear contenido increíble",
        ready: "¿Listo para Crear?",
        readySub: "Únete a miles de creadores haciendo contenido increíble",
        downloadLarge: "Descargar Porn Make",
        free: "Gratis para usar",
        noRegistration: "No se requiere registro",
        allDevices: "Funciona en todos los dispositivos",
        safe: "Seguro y protegido",
        visitSite: "Visitar Sitio Web",
        footerNote: "Hecho con ❤️ para creadores de contenido",
        madeBy: "Creación de contenido con IA"
    },
    fr: {
        title: "Porn Make",
        tagline: "Créez le Meilleur Porn Toujours",
        subtitle: "Plateforme intégrée à l'IA pour créer du contenu de haute qualité",
        download: "Télécharger l'Application",
        copyLink: "Copier le Lien",
        copied: "Copié!",
        welcome: "Bienvenue sur Porn Make",
        createMore: "Créez Plus Comme Ça",
        shareText: "Partagez Porn Make avec d'autres aussi. Copiez le lien et partagez avec d'autres.",
        linkToCopy: "Créons le meilleur porno toujours. Suivez le lien.",
        features: "Fonctionnalités",
        featuresSub: "Tout ce dont vous avez besoin pour créer du contenu incroyable",
        ready: "Prêt à Créer?",
        readySub: "Rejoignez des milliers de créateurs faisant du contenu incroyable",
        downloadLarge: "Télécharger Porn Make",
        free: "Gratuit à utiliser",
        noRegistration: "Aucune inscription requise",
        allDevices: "Fonctionne sur tous les appareils",
        safe: "Sûr et sécurisé",
        visitSite: "Visiter le Site",
        footerNote: "Fait avec ❤️ pour les créateurs de contenu",
        madeBy: "Création de contenu par IA"
    },
    de: {
        title: "Porn Make",
        tagline: "Mache den Besten Porn Immer",
        subtitle: "KI-integrierte Plattform zur Erstellung hochwertiger Inhalte",
        download: "App Herunterladen",
        copyLink: "Link Kopieren",
        copied: "Kopiert!",
        welcome: "Willkommen bei Porn Make",
        createMore: "Erstelle Mehr Wie Das",
        shareText: "Teile Porn Make auch mit anderen. Kopiere den Link und teile ihn mit anderen.",
        linkToCopy: "Lass uns den besten Porno immer machen. Folge dem Link.",
        features: "Funktionen",
        featuresSub: "Alles was du brauchst um erstaunliche Inhalte zu erstellen",
        ready: "Bereit zum Erstellen?",
        readySub: "Schließe dich Tausenden von Erstellern an die erstaunliche Inhalte machen",
        downloadLarge: "Porn Make Herunterladen",
        free: "Kostenlos nutzbar",
        noRegistration: "Keine Registrierung erforderlich",
        allDevices: "Funktioniert auf allen Geräten",
        safe: "Sicher und geschützt",
        visitSite: "Webseite Besuchen",
        footerNote: "Gemacht mit ❤️ für Content-Ersteller",
        madeBy: "KI-gesteuerte Content-Erstellung"
    },
    zh: {
        title: "Porn Make",
        tagline: "制作史上最好的成人内容",
        subtitle: "AI集成平台，用于创建高质量内容",
        download: "下载应用",
        copyLink: "复制链接",
        copied: "已复制！",
        welcome: "欢迎来到 Porn Make",
        createMore: "创建更多类似内容",
        shareText: "也与其他人分享 Porn Make。复制链接并与他人分享。",
        linkToCopy: "让我们制作史上最好的成人内容。点击链接。",
        features: "功能",
        featuresSub: "创建精彩内容所需的一切",
        ready: "准备好创建了吗？",
        readySub: "加入成千上万制作精彩内容的创作者",
        downloadLarge: "下载 Porn Make",
        free: "免费使用",
        noRegistration: "无需注册",
        allDevices: "适用于所有设备",
        safe: "安全可靠",
        visitSite: "访问网站",
        footerNote: "为内容创作者而制作 ❤️",
        madeBy: "AI驱动的内容创作"
    },
    hi: {
        title: "Porn Make",
        tagline: "सबसे अच्छा पॉर्न बनाएं",
        subtitle: "उच्च गुणवत्ता वाली सामग्री बनाने के लिए AI-एकीकृत प्लेटफॉर्म",
        download: "ऐप डाउनलोड करें",
        copyLink: "लिंक कॉपी करें",
        copied: "कॉपी किया गया!",
        welcome: "Porn Make में आपका स्वागत है",
        createMore: "इस तरह और बनाएं",
        shareText: "Porn Make को दूसरों के साथ भी साझा करें। लिंक कॉपी करें और दूसरों के साथ साझा करें।",
        linkToCopy: "आइए सबसे अच्छा पॉर्न बनाएं। लिंक का पालन करें।",
        features: "सुविधाएं",
        featuresSub: "अविश्वसनीय सामग्री बनाने के लिए आवश्यक सब कुछ",
        ready: "बनाने के लिए तैयार हैं?",
        readySub: "अविश्वसनीय सामग्री बनाने वाले हजारों निर्माताओं से जुड़ें",
        downloadLarge: "Porn Make डाउनलोड करें",
        free: "मुफ्त उपयोग",
        noRegistration: "पंजीकरण की आवश्यकता नहीं",
        allDevices: "सभी उपकरणों पर काम करता है",
        safe: "सुरक्षित और सुरक्षित",
        visitSite: "वेबसाइट जाएं",
        footerNote: "सामग्री निर्माताओं के लिए ❤️ के साथ बनाया गया",
        madeBy: "AI-संचालित सामग्री निर्माण"
    },
    pt: {
        title: "Porn Make",
        tagline: "Faça o Melhor Porn Sempre",
        subtitle: "Plataforma integrada com IA para criar conteúdo de alta qualidade",
        download: "Baixar Aplicativo",
        copyLink: "Copiar Link",
        copied: "Copiado!",
        welcome: "Bem-vindo ao Porn Make",
        createMore: "Crie Mais Como Isso",
        shareText: "Compartilhe Porn Make com outros também. Copie o link e compartilhe com outros.",
        linkToCopy: "Vamos criar o melhor pornô sempre. Siga o link.",
        features: "Recursos",
        featuresSub: "Tudo que você precisa para criar conteúdo incrível",
        ready: "Pronto para Criar?",
        readySub: "Junte-se a milhares de criadores fazendo conteúdo incrível",
        downloadLarge: "Baixar Porn Make",
        free: "Gratuito para usar",
        noRegistration: "Não requer registro",
        allDevices: "Funciona em todos os dispositivos",
        safe: "Seguro e protegido",
        visitSite: "Visitar Site",
        footerNote: "Feito com ❤️ para criadores de conteúdo",
        madeBy: "Criação de conteúdo com IA"
    }
};
