// PornMake Multi-language Translations
const translations = {
    en: {
        title: "Porn Make",
        badge: "🔥 #1 AI Porn Generator",
        welcome: "Create Stunning AI Porn",
        tagline: "Generate unlimited adult content with cutting-edge AI technology. Fast, easy, and free.",
        download: "Download Now",
        downloadIcon: "⬇️",
        apkSize: "APK • Free",
        feat1: "AI-Powered",
        feat2: "Instant Results",
        feat3: "Custom Styles",
        stat1: "10M+",
        stat1Label: "Downloads",
        stat2: "4.9★",
        stat2Label: "User Rating",
        stat3: "100%",
        stat3Label: "Free",
        featuresTitle: "Why Choose Porn Make?",
        card1Title: "Advanced AI",
        card1Desc: "State-of-the-art machine learning models for realistic results",
        card2Title: "Lightning Fast",
        card2Desc: "Generate content in seconds with our optimized AI engine",
        card3Title: "HD Quality",
        card3Desc: "Crystal clear high-definition output every time",
        card4Title: "Multiple Styles",
        card4Desc: "Choose from various artistic styles and preferences",
        card5Title: "100% Private",
        card5Desc: "Your data and creations stay on your device only",
        card6Title: "Mobile First",
        card6Desc: "Optimized for Android smartphones and tablets",
        howTitle: "How It Works",
        step1Title: "Download the App",
        step1Desc: "Get the APK file and install it on your Android device",
        step2Title: "Enter Your Prompt",
        step2Desc: "Describe what you want to create in detail",
        step3Title: "Get Instant Results",
        step3Desc: "Watch as AI brings your imagination to life in seconds",
        testimonialsTitle: "What Users Say",
        review1: "\"Absolutely amazing! The AI creates exactly what I imagine. Best app ever!\"",
        review2: "\"Incredible quality and super fast. Works perfectly on my phone.\"",
        review3: "\"Finally an app that delivers what it promises. Highly recommend!\"",
        user1: "Verified User",
        user2: "Happy Customer",
        user3: "Premium User",
        ctaTitle: "Ready to Create Amazing Content?",
        ctaSubtitle: "Join millions of users creating incredible AI-generated content",
        downloadLarge: "Download Porn Make",
        shareTitle: "Share with Friends",
        shareText: "Share the app and get access to exclusive features!",
        copyLink: "Copy Link",
        copied: "Copied!",
        downloadStarted: "Download started!"
    },
    ar: {
        title: "Porn Make",
        badge: "🔥 #1 مولد إباحي بالذكاء الاصطناعي",
        welcome: "إنشاء إباحي مذهل بالذكاء الاصطناعي",
        tagline: "أنشئ محتوى للبالغين غير محدود باستخدام تقنية الذكاء الاصطناعي المتطورة. سريع وسهل ومجاني.",
        download: "تحميل الآن",
        downloadIcon: "⬇️",
        apkSize: "APK • مجاني",
        feat1: "مدعوم بالذكاء الاصطناعي",
        feat2: "نتائج فورية",
        feat3: "أنماط مخصصة",
        stat1: "+10 مليون",
        stat1Label: "تحميل",
        stat2: "4.9★",
        stat2Label: "تقييم المستخدمين",
        stat3: "100%",
        stat3Label: "مجاني",
        featuresTitle: "لماذا تختار Porn Make؟",
        card1Title: "ذكاء اصطناعي متقدم",
        card1Desc: "نماذج تعلم الآلة المتطورة لنتائج واقعية",
        card2Title: "سريع كالبرق",
        card2Desc: "أنشئ المحتوى في ثوانٍ بمحرك AI المحسن",
        card3Title: "جودة HD",
        card3Desc: "إخراج عالي الوضوح واضح في كل مرة",
        card4Title: "أنماط متعددة",
        card4Desc: "اختر من بين الأنماط الفنية والتفضيلات المختلفة",
        card5Title: "خصوصية 100%",
        card5Desc: "بياناتك وإنشاءاتك تبقى على جهازك فقط",
        card6Title: "الجوال أولاً",
        card6Desc: "محسّن للهواتف الذكية والأجهزة اللوحية Android",
        howTitle: "كيف يعمل",
        step1Title: "قم بتحميل التطبيق",
        step1Desc: "احصل على ملف APK وقم بتثبيته على جهاز Android",
        step2Title: "أدخل مطالبتك",
        step2Desc: "صف ما تريد إنشاءه بالتفصيل",
        step3Title: "احصل على نتائج فورية",
        step3Desc: "شاهد as AI يحضّر خيالك للحياة في ثوانٍ",
        testimonialsTitle: "ماذا يقول المستخدمون",
        review1: "\"مذهل تمامًا! الذكاء الاصطناعي يخلق بالضبط ما أتخيل. أفضل تطبيق على الإطلاق!\"",
        review2: "\"جودة لا تصدق وسريع للغاية. يعمل بشكل مثالي على هاتفي.\"",
        review3: "\"أخيرًا تطبيق يقدم ما يعد به. أوصي بشدة!\"",
        user1: "مستخدم موثق",
        user2: "عميل سعيد",
        user3: "مستخدم مميز",
        ctaTitle: "هل أنت مستعد لإنشاء محتوى مذهل؟",
        ctaSubtitle: "انضم إلى ملايين المستخدمين الذين ينشئون محتوى مذهلًا مولدًا بالذكاء الاصطناعي",
        downloadLarge: "تحميل Porn Make",
        shareTitle: "شارك مع الأصدقاء",
        shareText: "شارك التطبيق واحصل على إمكانية الوصول إلى ميزات حصرية!",
        copyLink: "نسخ الرابط",
        copied: "تم النسخ!",
        downloadStarted: "بدأ التحميل!"
    },
    es: {
        title: "Porn Make",
        badge: "🔥 #1 Generador de Porno IA",
        welcome: "Crea Porno IA Increíble",
        tagline: "Genera contenido adulto ilimitado con tecnología de IA de vanguardia. Rápido, fácil y gratuito.",
        download: "Descargar Ahora",
        downloadIcon: "⬇️",
        apkSize: "APK • Gratis",
        feat1: "Impulsado por IA",
        feat2: "Resultados Instantáneos",
        feat3: "Estilos Personalizados",
        stat1: "10M+",
        stat1Label: "Descargas",
        stat2: "4.9★",
        stat2Label: "Calificación",
        stat3: "100%",
        stat3Label: "Gratis",
        featuresTitle: "¿Por Qué Elegir Porn Make?",
        card1Title: "IA Avanzada",
        card1Desc: "Modelos de aprendizaje automático de vanguardia para resultados realistas",
        card2Title: "Ultrarrápido",
        card2Desc: "Genera contenido en segundos con nuestro motor de IA optimizado",
        card3Title: "Calidad HD",
        card3Desc: "Salida de alta definición cristalina cada vez",
        card4Title: "Estilos Múltiples",
        card4Desc: "Elige entre varios estilos artísticos y preferencias",
        card5Title: "100% Privado",
        card5Desc: "Tus datos y creaciones se mantienen solo en tu dispositivo",
        card6Title: "Móvil Primero",
        card6Desc: "Optimizado para smartphones y tablets Android",
        howTitle: "Cómo Funciona",
        step1Title: "Descarga la Aplicación",
        step1Desc: "Obtén el archivo APK e instálalo en tu dispositivo Android",
        step2Title: "Ingresa Tu Prompt",
        step2Desc: "Describe lo que quieres crear en detalle",
        step3Title: "Obtén Resultados Instantáneos",
        step3Desc: "Observa cómo la IA da vida a tu imaginación en segundos",
        testimonialsTitle: "Lo Que Dicen Los Usuarios",
        review1: "\"¡Absolutamente increíble! La IA crea exactamente lo que imagino. ¡La mejor aplicación jamás!\"",
        review2: "\"Calidad increíble y súper rápido. Funciona perfectamente en mi teléfono.\"",
        review3: "\"¡Finalmente una aplicación que cumple lo que promete. ¡Muy recomendado!\"",
        user1: "Usuario Verificado",
        user2: "Cliente Feliz",
        user3: "Usuario Premium",
        ctaTitle: "¿Listo Para Crear Contenido Increíble?",
        ctaSubtitle: "Únete a millones de usuarios creando contenido increíble generado por IA",
        downloadLarge: "Descargar Porn Make",
        shareTitle: "Comparte Con Amigos",
        shareText: "¡Comparte la aplicación y obtén acceso a características exclusivas!",
        copyLink: "Copiar Enlace",
        copied: "¡Copiado!",
        downloadStarted: "¡Descarga iniciada!"
    },
    fr: {
        title: "Porn Make",
        badge: "🔥 #1 Générateur de Porno IA",
        welcome: "Créez du Porno IA Magnifique",
        tagline: "Générez du contenu adulte illimité avec une technologie IA de pointe. Rapide, facile et gratuit.",
        download: "Télécharger Maintenant",
        downloadIcon: "⬇️",
        apkSize: "APK • Gratuit",
        feat1: "Alimenté par l'IA",
        feat2: "Résultats Instantanés",
        feat3: "Styles Personnalisés",
        stat1: "10M+",
        stat1Label: "Téléchargements",
        stat2: "4.9★",
        stat2Label: "Note Utilisateur",
        stat3: "100%",
        stat3Label: "Gratuit",
        featuresTitle: "Pourquoi Choisir Porn Make?",
        card1Title: "IA Avancée",
        card1Desc: "Modèles d'apprentissage automatique de pointe pour des résultats réalistes",
        card2Title: "Ultra Rapide",
        card2Desc: "Générez du contenu en quelques secondes avec notre moteur IA optimisé",
        card3Title: "Qualité HD",
        card3Desc: "Sortie haute définition cristalline à chaque fois",
        card4Title: "Styles Multiples",
        card4Desc: "Choisissez parmi divers styles artistiques et préférences",
        card5Title: "100% Privé",
        card5Desc: "Vos données et créations restent uniquement sur votre appareil",
        card6Title: "Mobile D'Abord",
        card6Desc: "Optimisé pour les smartphones et tablettes Android",
        howTitle: "Comment Ça Marche",
        step1Title: "Téléchargez l'Application",
        step1Desc: "Obtenez le fichier APK et installez-le sur votre appareil Android",
        step2Title: "Entrez Votre Prompt",
        step2Desc: "Décrivez ce que vous voulez créer en détail",
        step3Title: "Obtenez Des Résultats Instantanés",
        step3Desc: "Regardez l'IA donner vie à votre imagination en quelques secondes",
        testimonialsTitle: "Ce Que Disent Les Utilisateurs",
        review1: "\"Absolument incroyable! L'IA crée exactement ce que j'imagine. Meilleure application jamais!\"",
        review2: "\"Qualité incroyable et super rapide. Fonctionne parfaitement sur mon téléphone.\"",
        review3: "\"Enfin une application qui tient ses promesses. Hautement recommandé!\"",
        user1: "Utilisateur Vérifié",
        user2: "Client Heureux",
        user3: "Utilisateur Premium",
        ctaTitle: "Prêt À Créer Du Contenu Incroyable?",
        ctaSubtitle: "Rejoignez des millions d'utilisateurs créant du contenu incroyable généré par IA",
        downloadLarge: "Télécharger Porn Make",
        shareTitle: "Partagez Avec Des Amis",
        shareText: "Partagez l'application et accédez à des fonctionnalités exclusives!",
        copyLink: "Copier le Lien",
        copied: "Copié!",
        downloadStarted: "Téléchargement démarré!"
    },
    de: {
        title: "Porn Make",
        badge: "🔥 #1 KI-Porno-Generator",
        welcome: "Erstelle atemberaubende KI-Pornos",
        tagline: "Generiere unbegrenzte Erwachseneninhalte mit modernster KI-Technologie. Schnell, einfach und kostenlos.",
        download: "Jetzt Herunterladen",
        downloadIcon: "⬇️",
        apkSize: "APK • Kostenlos",
        feat1: "KI-gesteuert",
        feat2: "Sofortige Ergebnisse",
        feat3: "Benutzerdefinierte Stile",
        stat1: "10M+",
        stat1Label: "Downloads",
        stat2: "4.9★",
        stat2Label: "Benutzerbewertung",
        stat3: "100%",
        stat3Label: "Kostenlos",
        featuresTitle: "Warum Porn Make Wählen?",
        card1Title: "Fortgeschrittene KI",
        card1Desc: "Modernste Machine-Learning-Modelle für realistische Ergebnisse",
        card2Title: "Blitzschnell",
        card2Desc: "Generieren Sie Inhalte in Sekunden mit我们的 optimierten KI-Motor",
        card3Title: "HD-Qualität",
        card3Desc: "Kristallklare High-Definition-Ausgabe jedes Mal",
        card4Title: "Mehrere Stile",
        card4Desc: "Wählen Sie aus verschiedenen künstlerischen Stilen und Vorlieben",
        card5Title: "100% Privat",
        card5Desc: "Ihre Daten und Kreationen bleiben nur auf Ihrem Gerät",
        card6Title: "Mobile First",
        card6Desc: "Optimiert für Android-Smartphones und -Tablets",
        howTitle: "So Funktionierts",
        step1Title: "App Herunterladen",
        step1Desc: "Laden Sie die APK-Datei herunter und installieren Sie sie auf Ihrem Android-Gerät",
        step2Title: "Geben Sie Ihren Prompt Ein",
        step2Desc: "Beschreiben Sie detailliert, was Sie erstellen möchten",
        step3Title: "Erhalten Sie Sofortige Ergebnisse",
        step3Desc: "Sehen Sie zu, wie KI Ihre Vorstellungskraft in Sekunden zum Leben erweckt",
        testimonialsTitle: "Was Benutzer Sagen",
        review1: "\"Absolut erstaunlich! Die KI erstellt genau das, was ich mir vorstelle. Beste App je!\"",
        review2: "\"Unglaubliche Qualität und superschnell. Funktioniert perfekt auf meinem Telefon.\"",
        review3: "\"Endlich eine App, die das hält, was sie verspricht. Sehr empfohlen!\"",
        user1: "Verifizierter Benutzer",
        user2: "Zufriedener Kunde",
        user3: "Premium-Benutzer",
        ctaTitle: "Bereit, Erstaunliche Inhalte Zu Erstellen?",
        ctaSubtitle: "Schließen Sie sich Millionen von Benutzern an, die unglaubliche KI-generierte Inhalte erstellen",
        downloadLarge: "Porn Make Herunterladen",
        shareTitle: "Mit Freunden Teilen",
        shareText: "Teilen Sie die App und erhalten Sie Zugang zu exklusiven Funktionen!",
        copyLink: "Link Kopieren",
        copied: "Kopiert!",
        downloadStarted: "Download gestartet!"
    },
    zh: {
        title: "Porn Make",
        badge: "🔥 #1 AI色情生成器",
        welcome: "创建令人惊叹的AI色情内容",
        tagline: "使用尖端AI技术生成无限成人内容。快速、简单、免费。",
        download: "立即下载",
        downloadIcon: "⬇️",
        apkSize: "APK • 免费",
        feat1: "AI驱动",
        feat2: "即时结果",
        feat3: "自定义样式",
        stat1: "1000万+",
        stat1Label: "下载量",
        stat2: "4.9★",
        stat2Label: "用户评分",
        stat3: "100%",
        stat3Label: "免费",
        featuresTitle: "为什么选择 Porn Make?",
        card1Title: "先进AI",
        card1Desc: "最先进的机器学习模型，呈现逼真效果",
        card2Title: "闪电般快速",
        card2Desc: "使用我们优化的AI引擎在几秒钟内生成内容",
        card3Title: "高清质量",
        card3Desc: "每次都呈现清晰的高清输出",
        card4Title: "多种风格",
        card4Desc: "从各种艺术风格和偏好中选择",
        card5Title: "100%私密",
        card5Desc: "您的数据和创作仅保留在您的设备上",
        card6Title: "移动优先",
        card6Desc: "针对Android智能手机和平板电脑优化",
        howTitle: "如何工作",
        step1Title: "下载应用",
        step1Desc: "获取APK文件并在您的Android设备上安装",
        step2Title: "输入您的提示词",
        step2Desc: "详细描述您想要创建的内容",
        step3Title: "立即获取结果",
        step3Desc: "观看AI在几秒钟内将您的想象变为现实",
        testimonialsTitle: "用户评价",
        review1: "\"绝对令人惊叹！AI完全按照我的想象创建。有史以来最好的应用！\"",
        review2: "\"令人难以置信的质量，超快速度。在我的手机上完美运行。\"",
        review3: "\"终于有一款应用兑现了它的承诺。强烈推荐！\"",
        user1: "已验证用户",
        user2: "满意客户",
        user3: "高级用户",
        ctaTitle: "准备好创建精彩内容了吗？",
        ctaSubtitle: "加入数百万创建令人难以置信的AI生成内容的用户",
        downloadLarge: "下载 Porn Make",
        shareTitle: "与朋友分享",
        shareText: "分享应用并获得独家功能访问权限！",
        copyLink: "复制链接",
        copied: "已复制！",
        downloadStarted: "下载已开始！"
    },
    hi: {
        title: "Porn Make",
        badge: "🔥 #1 AI पोर्न जेनरेटर",
        welcome: "शानदार AI पोर्न बनाएं",
        tagline: "अत्याधुनिक AI तकनीक के साथ असीमित वयस्क सामग्री बनाएं। तेज, आसान और निःशुल्क।",
        download: "अभी डाउनलोड करें",
        downloadIcon: "⬇️",
        apkSize: "APK • मुफ्त",
        feat1: "AI-संचालित",
        feat2: "त्वरित परिणाम",
        feat3: "कस्टम शैलियां",
        stat1: "10M+",
        stat1Label: "डाउनलोड",
        stat2: "4.9★",
        stat2Label: "उपयोगकर्ता रेटिंग",
        stat3: "100%",
        stat3Label: "मुफ्त",
        featuresTitle: "Porn Make क्यों चुनें?",
        card1Title: "उन्नत AI",
        card1Desc: "यथार्थवादी परिणामों के लिए अत्याधुनिक मशीन लर्निंग मॉडल",
        card2Title: "बिजली की गति",
        card2Desc: "हमारे अनुकूलित AI इंजन के साथ सेकंड में सामग्री बनाएं",
        card3Title: "HD गुणवत्ता",
        card3Desc: "हर बार स्पष्ट उच्च परिभाषा आउटपुट",
        card4Title: "कई शैलियां",
        card4Desc: "विभिन्न कलात्मक शैलियों और प्राथमिकताओं में से चुनें",
        card5Title: "100% निजी",
        card5Desc: "आपका डेटा और निर्माण केवल आपके डिवाइस पर रहता है",
        card6Title: "मोबाइल पहले",
        card6Desc: "Android स्मार्टफोन और टैबलेट के लिए अनुकूलित",
        howTitle: "यह कैसे काम करता है",
        step1Title: "ऐप डाउनलोड करें",
        step1Desc: "APK फ़ाइल प्राप्त करें और अपने Android डिवाइस पर इंस्टॉल करें",
        step2Title: "अपना प्रॉम्प्ट दर्ज करें",
        step2Desc: "विस्तार से बताएं कि आप क्या बनाना चाहते हैं",
        step3Title: "तुरंत परिणाम प्राप्त करें",
        step3Desc: "देखें कि कैसे AI सेकंड में आपकी कल्पना को जीवन देता है",
        testimonialsTitle: "उपयोगकर्ताओं के विचार",
        review1: "\"बिल्कुल अद्भुत! AI बिल्कुल वही बनाता है जो मैं कल्पना करता हूं। सबसे अच्छा ऐप कभी!\"",
        review2: "\"अविश्वसनीय गुणवत्ता और बहुत तेज़। मेरे फोन पर बिल्कुल सही काम करता है।\"",
        review3: "\"आखिरकार एक ऐप जो वादा किया वह देता है। अत्यधिक अनुशंसित!\"",
        user1: "सत्यापित उपयोगकर्ता",
        user2: "खुश ग्राहक",
        user3: "प्रीमियम उपयोगकर्ता",
        ctaTitle: "अविश्वसनीय सामग्री बनाने के लिए तैयार हैं?",
        ctaSubtitle: "अविश्वसनीय AI-जनित सामग्री बनाने वाले लाखों उपयोगकर्ताओं में शामिल हों",
        downloadLarge: "Porn Make डाउनलोड करें",
        shareTitle: "मित्रों के साथ साझा करें",
        shareText: "ऐप शेयर करें और विशेष सुविधाओं तक पहुंचें!",
        copyLink: "लिंक कॉपी करें",
        copied: "कॉपी किया गया!",
        downloadStarted: "डाउनलोड शुरू हो गया!"
    },
    pt: {
        title: "Porn Make",
        badge: "🔥 #1 Gerador de Porno IA",
        welcome: "Crie Porno IA Incrível",
        tagline: "Gere conteúdo adulto ilimitado com tecnologia de IA de ponta. Rápido, fácil e grátis.",
        download: "Baixar Agora",
        downloadIcon: "⬇️",
        apkSize: "APK • Grátis",
        feat1: "Movido por IA",
        feat2: "Resultados Instantâneos",
        feat3: "Estilos Personalizados",
        stat1: "10M+",
        stat1Label: "Downloads",
        stat2: "4.9★",
        stat2Label: "Avaliação",
        stat3: "100%",
        stat3Label: "Grátis",
        featuresTitle: "Por Que Escolher Porn Make?",
        card1Title: "IA Avançada",
        card1Desc: "Modelos de aprendizado de máquina de ponta para resultados realistas",
        card2Title: "Ultra Rápido",
        card2Desc: "Gere conteúdo em segundos com nosso mecanismo de IA otimizado",
        card3Title: "Qualidade HD",
        card3Desc: "Saída de alta definição cristalina toda vez",
        card4Title: "Múltiplos Estilos",
        card4Desc: "Escolha entre vários estilos artísticos e preferências",
        card5Title: "100% Privado",
        card5Desc: "Seus dados e criações ficam apenas no seu dispositivo",
        card6Title: "Mobile First",
        card6Desc: "Otimizado para smartphones e tablets Android",
        howTitle: "Como Funciona",
        step1Title: "Baixe o Aplicativo",
        step1Desc: "Obtenha o arquivo APK e instale no seu dispositivo Android",
        step2Title: "Digite Seu Prompt",
        step2Desc: "Descreva o que você quer criar em detalhes",
        step3Title: "Obtenha Resultados Instantâneos",
        step3Desc: "Veja a IA dar vida à sua imaginação em segundos",
        testimonialsTitle: "O Que Os Usuários Dizem",
        review1: "\"Absolutamente incrível! A IA cria exatamente o que imagino. Melhor app já!\"",
        review2: "\"Qualidade incrível e super rápido. Funciona perfeitamente no meu telefone.\"",
        review3: "\"Finalmente um app que entrega o que promete. Altamente recomendado!\"",
        user1: "Usuário Verificado",
        user2: "Cliente Feliz",
        user3: "Usuário Premium",
        ctaTitle: "Pronto Para Criar Conteúdo Incrível?",
        ctaSubtitle: "Junte-se a milhões de usuários criando conteúdo incrível gerado por IA",
        downloadLarge: "Baixar Porn Make",
        shareTitle: "Compartilhe Com Amigos",
        shareText: "Compartilhe o app e ganhe acesso a recursos exclusivos!",
        copyLink: "Copiar Link",
        copied: "Copiado!",
        downloadStarted: "Download iniciado!"
    }
};
