// PornMake Multi-language Translations
const translations = {
    en: {
        title: "Porn Make",
        badge: "🔥 #1 AI Porn Generator",
        welcome: "Create Stunning AI Porn",
        tagline: "Generate unlimited adult content with cutting-edge AI technology. Fast, easy, and free.",
        download: "Download Now",
        downloadIcon: "⬇️",
        feat1: "AI-Powered",
        feat2: "Instant Results",
        feat3: "Custom Styles",
        stat1: "10M+",
        stat1Label: "Downloads",
        stat2: "4.9★",
        stat2Label: "User Rating",
        stat3: "100%",
        stat3Label: "Free",
        howTitle: "How It Works",
        step1: "Download the app",
        step2: "Enter your prompt",
        step3: "Get AI-generated content instantly",
        shareText: "Share with friends and get more content!",
        copyLink: "Copy Link",
        copied: "Copied!",
        downloadStarted: "Download started!"
    },
    ar: {
        title: "Porn Make",
        badge: "🔥 #1 مولد إباحي بالذكاء الاصطناعي",
        welcome: "إنشاء إباحي مذهل بالذكاء الاصطناعي",
        tagline: "أنشئ محتوى للبالغين غير محدود باستخدام تقنية الذكاء الاصطناعي المتطورة. سريع وسهل ومجاني.",
        download: "تحميل الآن",
        downloadIcon: "⬇️",
        feat1: "مدعوم بالذكاء الاصطناعي",
        feat2: "نتائج فورية",
        feat3: "أنماط مخصصة",
        stat1: "+10 مليون",
        stat1Label: "تحميل",
        stat2: "4.9★",
        stat2Label: "تقييم المستخدمين",
        stat3: "100%",
        stat3Label: "مجاني",
        howTitle: "كيف يعمل",
        step1: "قم بتحميل التطبيق",
        step2: "أدخل مطالبتك",
        step3: "احصل على محتوى مولد بالذكاء الاصطناعي فوراً",
        shareText: "شارك مع الأصدقاء واحصل على المزيد من المحتوى!",
        copyLink: "نسخ الرابط",
        copied: "تم النسخ!",
        downloadStarted: "بدأ التحميل!"
    },
    es: {
        title: "Porn Make",
        badge: "🔥 #1 Generador de Porno IA",
        welcome: "Crea Porno IA Increíble",
        tagline: "Genera contenido adulto ilimitado con tecnología de IA de vanguardia. Rápido, fácil y gratuito.",
        download: "Descargar Ahora",
        downloadIcon: "⬇️",
        feat1: "Impulsado por IA",
        feat2: "Resultados Instantáneos",
        feat3: "Estilos Personalizados",
        stat1: "10M+",
        stat1Label: "Descargas",
        stat2: "4.9★",
        stat2Label: "Calificación",
        stat3: "100%",
        stat3Label: "Gratis",
        howTitle: "Cómo Funciona",
        step1: "Descarga la aplicación",
        step2: "Ingresa tu prompt",
        step3: "Obtén contenido generado por IA al instante",
        shareText: "¡Comparte con amigos y obtén más contenido!",
        copyLink: "Copiar Enlace",
        copied: "¡Copiado!",
        downloadStarted: "¡Descarga iniciada!"
    },
    fr: {
        title: "Porn Make",
        badge: "🔥 #1 Générateur de Porno IA",
        welcome: "Créez du Porno IA Magnifique",
        tagline: "Générez du contenu adulte illimité avec une technologie IA de pointe. Rapide, facile et gratuit.",
        download: "Télécharger Maintenant",
        downloadIcon: "⬇️",
        feat1: "Alimenté par l'IA",
        feat2: "Résultats Instantanés",
        feat3: "Styles Personnalisés",
        stat1: "10M+",
        stat1Label: "Téléchargements",
        stat2: "4.9★",
        stat2Label: "Note Utilisateur",
        stat3: "100%",
        stat3Label: "Gratuit",
        howTitle: "Comment Ça Marche",
        step1: "Téléchargez l'application",
        step2: "Entrez votre prompt",
        step3: "Obtenez du contenu généré par IA instantanément",
        shareText: "Partagez avec des amis et obtenez plus de contenu!",
        copyLink: "Copier le Lien",
        copied: "Copié!",
        downloadStarted: "Téléchargement démarré!"
    },
    de: {
        title: "Porn Make",
        badge: "🔥 #1 KI-Porno-Generator",
        welcome: "Erstelle atemberaubende KI-Pornos",
        tagline: "Generiere unbegrenzte Erwachseneninhalte mit modernster KI-Technologie. Schnell, einfach und kostenlos.",
        download: "Jetzt Herunterladen",
        downloadIcon: "⬇️",
        feat1: "KI-gesteuert",
        feat2: "Sofortige Ergebnisse",
        feat3: "Benutzerdefinierte Stile",
        stat1: "10M+",
        stat1Label: "Downloads",
        stat2: "4.9★",
        stat2Label: "Benutzerbewertung",
        stat3: "100%",
        stat3Label: "Kostenlos",
        howTitle: "So Funktionierts",
        step1: "App herunterladen",
        step2: "Geben Sie Ihren Prompt ein",
        step3: "Erhalten Sie sofort KI-generierte Inhalte",
        shareText: "Teile mit Freunden und erhalte mehr Inhalte!",
        copyLink: "Link Kopieren",
        copied: "Kopiert!",
        downloadStarted: "Download gestartet!"
    },
    zh: {
        title: "Porn Make",
        badge: "🔥 #1 AI色情生成器",
        welcome: "创建令人惊叹的AI色情内容",
        tagline: "使用尖端AI技术生成无限成人内容。快速、简单、免费。",
        download: "立即下载",
        downloadIcon: "⬇️",
        feat1: "AI驱动",
        feat2: "即时结果",
        feat3: "自定义样式",
        stat1: "1000万+",
        stat1Label: "下载量",
        stat2: "4.9★",
        stat2Label: "用户评分",
        stat3: "100%",
        stat3Label: "免费",
        howTitle: "如何工作",
        step1: "下载应用",
        step2: "输入您的提示词",
        step3: "立即获取AI生成的内容",
        shareText: "与朋友分享并获得更多内容！",
        copyLink: "复制链接",
        copied: "已复制！",
        downloadStarted: "下载已开始！"
    },
    hi: {
        title: "Porn Make",
        badge: "🔥 #1 AI पोर्न जेनरेटर",
        welcome: "शानदार AI पोर्न बनाएं",
        tagline: "अत्याधुनिक AI तकनीक के साथ असीमित वयस्क सामग्री बनाएं। तेज, आसान और निःशुल्क।",
        download: "अभी डाउनलोड करें",
        downloadIcon: "⬇️",
        feat1: "AI-संचालित",
        feat2: "त्वरित परिणाम",
        feat3: "कस्टम शैलियां",
        stat1: "10M+",
        stat1Label: "डाउनलोड",
        stat2: "4.9★",
        stat2Label: "उपयोगकर्ता रेटिंग",
        stat3: "100%",
        stat3Label: "मुफ्त",
        howTitle: "यह कैसे काम करता है",
        step1: "ऐप डाउनलोड करें",
        step2: "अपना प्रॉम्प्ट दर्ज करें",
        step3: "तुरंत AI-जनित सामग्री प्राप्त करें",
        shareText: "दोस्तों के साथ साझा करें और अधिक सामग्री प्राप्त करें!",
        copyLink: "लिंक कॉपी करें",
        copied: "कॉपी किया गया!",
        downloadStarted: "डाउनलोड शुरू हो गया!"
    },
    pt: {
        title: "Porn Make",
        badge: "🔥 #1 Gerador de Porno IA",
        welcome: "Crie Porno IA Incrível",
        tagline: "Gere conteúdo adulto ilimitado com tecnologia de IA de ponta. Rápido, fácil e grátis.",
        download: "Baixar Agora",
        downloadIcon: "⬇️",
        feat1: "Movido por IA",
        feat2: "Resultados Instantâneos",
        feat3: "Estilos Personalizados",
        stat1: "10M+",
        stat1Label: "Downloads",
        stat2: "4.9★",
        stat2Label: "Avaliação",
        stat3: "100%",
        stat3Label: "Grátis",
        howTitle: "Como Funciona",
        step1: "Baixe o aplicativo",
        step2: "Digite seu prompt",
        step3: "Obtenha conteúdo gerado por IA instantaneamente",
        shareText: "Compartilhe com amigos e obtenha mais conteúdo!",
        copyLink: "Copiar Link",
        copied: "Copiado!",
        downloadStarted: "Download iniciado!"
    }
};
